on: pull_request

jobs:
  example_comment_pr:
    runs-on: ubuntu-latest
    name: comment on PR.
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: |
            Nice work on adding the problem to the board ! 🚀
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
